name: download_file
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas=2.1.3
  - pytest=7.0.0
  - pip=23.3.1
  - requests=2.24.0
  - gcc
  - pyarrow=10.0.1
  - numpy=1.24
  - pip:
      - mlflow==2.8.1
      - wandb==0.16.0
      - git+https://github.com/DRroth76/Project-Build-an-ML-Pipeline-Starter.git#egg=wandb-utils&subdirectory=components
